# 1. Regular Expression

In [1]:
import re

myData = "I am little boy please give me icecream"
x=re.search("boy",myData)
print(x)

<_sre.SRE_Match object; span=(12, 15), match='boy'>


## 1.2. How to print?

In [3]:
import re

myData = "I am little boy please give me icecream"
x=re.search("boy",myData)
if x:
    print("Boy exist in myData")
else:
    print("Boy donot exist in myData")


Boy exist in myData


## 1.3. findall() in String

In [6]:
import re

myData = "I am little boy please give me icecream"
x=re.findall("a",myData)
print(x)

['a', 'a', 'a']


## 1.4. Search Word Position in String

In [9]:
import re

myData = "I am little boy please give me icecream"
x=re.search("\s",myData) #s denote space
print(x.start())

1


## 1.5. Split a String

In [10]:
import re

myData = "I am little boy please give me icecream"
x=re.split("please",myData)
print(x)

['I am little boy ', ' give me icecream']


## 1.6. Subsitute a String

In [12]:
import re

myData = "I am little boy please give me icecream"
x=re.sub("a","9",myData)
print(x)

I 9m little boy ple9se give me icecre9m


In [15]:
txt = "The rain in Spain"
x = re.search(r"\bS\w+",txt)
#"r" means read and then write first word start from "S".

print(x.group())

Spain


## 1.7. Try and Except in Python

In [20]:
try:
    print(y)
except:
    print("Hello")

Hello


## 1.8. Finally Key Word

In [21]:
try:
    print(y)
except:
    print("Y is not iitiallized!")
finally:
    a=10
    b=12
    add = a + b
    print(add)

Y is not iitiallized!
22


## 1.9. Raise an Exception

In [22]:
x = -1

if x < 0:
    raise Exception("Sorry, no number less than 0 is allowed")

Exception: Sorry, no number less than 0 is allowed

## 1.10 NumPy

In [24]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]


In [25]:
x = np.array(32)
print(x)
print(type(x))

32
<class 'numpy.ndarray'>


## 1.11. 2D Arrays

In [26]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


## 1.12. Dimensions of Array

In [27]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [30]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print("2nd Element of 1st row:", arr[0][1])

2nd Element of 1st row: 2
